# Generated by Django 2.2.4 on 2021-05-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210506_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='customer_request',
        ),
        migrations.AddField(
            model_name='request',
            name='offer_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='app.Freelancer'),
        ),
    ]
