# Generated by Django 2.2.4 on 2021-05-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210506_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer1', to='app.Customer'),
        ),
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='app.Project'),
        ),
    ]
